name: Unit Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  label:
      name: "Static Type Checker"
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Install dependencies
          run: |
            sudo apt update
            sudo apt install pulseaudio-utils
            cat /etc/pulse/client.conf
            pactl info
